// Code generated by goctl. DO NOT EDIT.
package types

type CreateTimerRequest struct {
	App             string          `json:"app"`
	Name            string          `json:"name"`
	Status          int32           `json:"status"`
	Cron            string          `json:"cron"`
	NotifyHTTPParam NotifyHTTPParam `json:"notifyHTTPParam"`
}

type DisableTimerRequest struct {
	App     string `json:"app"`
	TimerId int64  `json:"timerId,omitempty"`
}

type EnableTimerRequest struct {
	App     string `json:"app"`
	TimerId int64  `json:"timerId,omitempty"`
}

type NotifyHTTPParam struct {
	Url     string            `json:"url"`
	Method  string            `json:"method"`
	Headers map[string]string `json:"headers"`
	Body    string            `json:"body"`
}

type Response struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
	Data    string `json:"data"`
	TraceID string `json:"trace_id"`
}
